#!/usr/bin/env bash
# Generates .cargo/config.toml from a single source of truth.
# Usage: scripts/cargo/generate-cargo-config.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$REPO_ROOT/.cargo/config.toml"

# ── shared flag fragments ────────────────────────────────────────────

COMMON=(
  '--cfg'  'tokio_unstable'
  '-Zshare-generics=y'
)

PERF=(
  '-Zthreads=8'
  '-Csymbol-mangling-version=v0'
)

LLD_SELF_CONTAINED=(
  '-Zunstable-options'
  '-Clinker-flavor=gnu-lld-cc'
  '-Clink-self-contained=+linker'
)

# ── helpers ──────────────────────────────────────────────────────────

# Print a TOML array of strings from positional args.
# Embedded double-quotes are escaped for valid TOML.
toml_array() {
  local first=true
  printf '['
  for v in "$@"; do
    $first || printf ','
    first=false
    local escaped="${v//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '\n  "%s"' "$escaped"
  done
  printf '\n]\n'
}

# ── generate ─────────────────────────────────────────────────────────

cat > "$OUT" << 'HEADER'
# !! DO NOT EDIT — generated by scripts/cargo/generate-cargo-config.sh !!

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
TURBO_PNPM_WORKSPACE_DIR = { value = "", relative = true }

[alias]
xtask = "run --package xtask --"

HEADER

{

# ── [build] (default) ───────────────────────────────────────────────

printf '[build]\n'
printf 'rustflags = '
toml_array "${COMMON[@]}" "${PERF[@]}"
printf 'rustdocflags = []\n\n'

# ── x86_64 Windows ──────────────────────────────────────────────────

printf '[target.x86_64-pc-windows-msvc]\n'
printf 'linker = "rust-lld"\n'
printf 'rustflags = '
toml_array "${COMMON[@]}" "${PERF[@]}" \
  '-C' 'target-feature=+crt-static'

printf '\n'

# ── i686 Windows ─────────────────────────────────────────────────────

printf '[target.i686-pc-windows-msvc]\n'
printf 'linker = "rust-lld"\n'
printf 'rustflags = '
toml_array "${COMMON[@]}" "${PERF[@]}" \
  '-C' 'target-feature=+crt-static'

printf '\n'

# ── Linux GNU (all arches via cfg()) ────────────────────────────────

printf "[target.'cfg(all(target_os = \"linux\", target_env = \"gnu\"))']\n"
printf 'rustflags = '
toml_array "${COMMON[@]}" "${PERF[@]}" \
  "${LLD_SELF_CONTAINED[@]}"

printf '\n'

# ── aarch64 Linux MUSL ──────────────────────────────────────────────

printf '[target.aarch64-unknown-linux-musl]\n'
printf 'rustflags = '
toml_array "${COMMON[@]}" "${PERF[@]}" \
  '-Ctarget-feature=-crt-static' \
  '-Clink-arg=-lgcc' \
  "${LLD_SELF_CONTAINED[@]}"

printf '\n'

# ── x86_64 Linux MUSL ───────────────────────────────────────────────

printf '[target.x86_64-unknown-linux-musl]\n'
printf 'rustflags = '
toml_array "${COMMON[@]}" "${PERF[@]}" \
  '-Ctarget-feature=-crt-static' \
  "${LLD_SELF_CONTAINED[@]}"

printf '\n'

# ── armv7 GNU ────────────────────────────────────────────────────────

printf '[target.armv7-unknown-linux-gnueabihf]\n'
printf 'linker = "arm-linux-gnueabihf-gcc"\n\n'

# ── wasm32 ───────────────────────────────────────────────────────────

printf '[target.wasm32-unknown-unknown]\n'
printf 'rustflags = '
toml_array '-Zshare-generics=y' '--cfg' 'getrandom_backend="wasm_js"'

} >> "$OUT"

echo "Generated $OUT"
