#!/usr/bin/env bash
# Generates .cargo/config.toml and .github/rustflags.yml from a single source of truth.
#
# .cargo/config.toml    — consumed by cargo directly
# .github/rustflags.yml — RUSTFLAGS per target, set via $GITHUB_ENV in CI where
#                          napi CLI overrides .cargo/config.toml (see build_and_deploy.yml)
#
# Usage: scripts/cargo/generate-cargo-config.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT_TOML="$REPO_ROOT/.cargo/config.toml"
OUT_YAML="$REPO_ROOT/.github/rustflags.yml"

# ── shared flag fragments ────────────────────────────────────────────

COMMON=(
  '--cfg'  'tokio_unstable'
  '-Zshare-generics=y'
)

PERF=(
  '-Zthreads=8'
  '-Csymbol-mangling-version=v0'
)

LLD_SELF_CONTAINED=(
  '-Zunstable-options'
  '-Clinker-flavor=gnu-lld-cc'
  '-Clink-self-contained=+linker'
)

# ── helpers ──────────────────────────────────────────────────────────

# Print a TOML array of strings from positional args.
# Embedded double-quotes are escaped for valid TOML.
toml_array() {
  local first=true
  printf '['
  for v in "$@"; do
    $first || printf ','
    first=false
    local escaped="${v//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '\n  "%s"' "$escaped"
  done
  printf '\n]\n'
}

# Print space-joined flags from positional args.
space_flags() {
  echo "$*"
}

# ── per-target flag sets ─────────────────────────────────────────────
# Each *_FLAGS array is used to generate both config.toml and rustflags.yml.

BUILD_FLAGS=("${COMMON[@]}" "${PERF[@]}")

GNU_LINUX_FLAGS=("${COMMON[@]}" "${PERF[@]}" "${LLD_SELF_CONTAINED[@]}")

X86_64_MUSL_FLAGS=("${COMMON[@]}" "${PERF[@]}" '-Ctarget-feature=-crt-static' "${LLD_SELF_CONTAINED[@]}")

# aarch64-musl is cross-compiled on x86_64, so self-contained LLD doesn't work
# (Rust's bundled gcc-ld resolves to the host sysroot). Use the system cross-linker instead.
AARCH64_MUSL_FLAGS=("${COMMON[@]}" "${PERF[@]}" '-Ctarget-feature=-crt-static' '-Clink-arg=-lgcc')

X86_64_WIN_FLAGS=("${COMMON[@]}" "${PERF[@]}" '-C' 'target-feature=+crt-static')

I686_WIN_FLAGS=("${COMMON[@]}" "${PERF[@]}" '-C' 'target-feature=+crt-static')

# ── generate config.toml ─────────────────────────────────────────────

cat > "$OUT_TOML" << 'HEADER'
# !! DO NOT EDIT — generated by scripts/cargo/generate-cargo-config.sh !!

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
TURBO_PNPM_WORKSPACE_DIR = { value = "", relative = true }

[alias]
xtask = "run --package xtask --"

HEADER

{

printf '[build]\n'
printf 'rustflags = '
toml_array "${BUILD_FLAGS[@]}"
printf 'rustdocflags = []\n\n'

printf '[target.x86_64-pc-windows-msvc]\n'
printf 'linker = "rust-lld"\n'
printf 'rustflags = '
toml_array "${X86_64_WIN_FLAGS[@]}"
printf '\n'

printf '[target.i686-pc-windows-msvc]\n'
printf 'linker = "rust-lld"\n'
printf 'rustflags = '
toml_array "${I686_WIN_FLAGS[@]}"
printf '\n'

printf "[target.'cfg(all(target_os = \"linux\", target_env = \"gnu\"))']\n"
printf 'rustflags = '
toml_array "${GNU_LINUX_FLAGS[@]}"
printf '\n'

printf '[target.aarch64-unknown-linux-musl]\n'
printf 'linker = "aarch64-linux-musl-gcc"\n'
printf 'rustflags = '
toml_array "${AARCH64_MUSL_FLAGS[@]}"
printf '\n'

printf '[target.x86_64-unknown-linux-musl]\n'
printf 'rustflags = '
toml_array "${X86_64_MUSL_FLAGS[@]}"
printf '\n'

printf '[target.armv7-unknown-linux-gnueabihf]\n'
printf 'linker = "arm-linux-gnueabihf-gcc"\n\n'

printf '[target.wasm32-unknown-unknown]\n'
printf 'rustflags = '
toml_array '-Zshare-generics=y' '--cfg' 'getrandom_backend="wasm_js"'

} >> "$OUT_TOML"

echo "Generated $OUT_TOML"

# ── generate rustflags.yml ───────────────────────────────────────────
# This file provides RUSTFLAGS per target for CI workflows where the
# napi CLI overrides .cargo/config.toml by setting RUSTFLAGS itself.

cat > "$OUT_YAML" << YAML
# !! DO NOT EDIT — generated by scripts/cargo/generate-cargo-config.sh !!
# Pre-computed RUSTFLAGS per target, sourced by CI to override napi CLI defaults.

x86_64-unknown-linux-gnu: '$(space_flags "${GNU_LINUX_FLAGS[@]}")'
aarch64-unknown-linux-gnu: '$(space_flags "${GNU_LINUX_FLAGS[@]}")'
x86_64-unknown-linux-musl: '$(space_flags "${X86_64_MUSL_FLAGS[@]}")'
aarch64-unknown-linux-musl: '$(space_flags "${AARCH64_MUSL_FLAGS[@]}")'
YAML

echo "Generated $OUT_YAML"
